[tool.poetry]
name = "meierlab"
version = "0.1.0"
description = "Meier Lab tools"
authors = ["Lezlie Espana"]
license = "None"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[tool.poetry.group.test.dependencies]
pytest = "^7.2.1"
pytest-cov = "^4.0.0"


[tool.poetry.group.docs.dependencies]
scriv = {extras = ["toml"], version = "^1.2.0"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.scriv]
format = "md"
